name: 02 Condition steps

on:
  workflow_dispatch: # this even triggers the workflow manually

jobs:
  go_through_steps:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Exit Code 0
      id: successful_step
      run: |
        echo "Exit code 0"
        exit 0 
      shell: bash
    
    - name: Step 2 - Execute If Previous Succeeded
      if: ${{ success() }}
      run: |
        echo "running because previous step has succeeded"
    
    - name: Step 3 - I am Falling
      run: |
        echo "I am falling"
        exit 1
  
    - name: Step 4 - I will never execute
      run: |
        echo "I will never execute"

    - name: Step 5 - Execute on Workflow Failure
      if: ${{ failure() }}
      run: |
        echo "Workflow failed"
