name: 04 workflow_dispach

on: 
    workflow_dispach:
        inputs:
            username:
                description: 'Username'
                default: 'Michal'
                required: true
                type: string
            age:
                description: 'Age'
                required: true
                type: numbrer 

jobs:
    echo-username-age:
        runs-on:
            -   name: Echo Username and Age
                run: |
                    echo "Username: ${{ inputs.username}}"
                    echo "Age: ${{ inputs.age}}"