name: 06 Passing Data Between Steps

on:
  workflow_dispatch

jobs: 
  data-passing:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        id: sender
        run: |
          echo "name=Jaromir" >> $GITHUB_OUTPUT
      - name: Receive data
        run: |
          echo ${{ steps.sedner.outputs.name}}