name: 08 Secrets And Variables

on:
  workflow_dispatch:

jobs:
  build-on-deploy:
    runs-on: ubuntu-latest

    env:
      DEPlOYMENT_ENV: 'production'
    
    steps:
    - name: Build
      run: | 
        # Build your aplictation here
        echo "Building the aplication"
        echo ${{secrets.API_KEY}}
        echo ${{env.DEPLOYMENT_ENV}}
        echo $SECRET_API_KEY
        echo $CONFIG_VARIABLES
        echo $STEPS_USERNAME
        echo ${{vars.USERNAME}}

      env:
        SECRET_API_KEY: ${{secrets.API_KEY}}
        STEPS_USERNAME: ${{vars.USERNAME}}
        CONFIG_VARIABLES: ${{env.DEPLOYMENT_ENV}}
    
    - name: Deploy
      run: |
        echo "Global job variable ${{env.DEPLOYMENT_ENV}}"
        echo "Variable form previous step ${CONFIG_VARIABLE} enviroment"
        echo "VAriable from this step ${CONFIG_VARIABLES2} enviroment"
        echo "Local step variable ${ANOTHER_VARIABLE}"
        echo "Local step variable (without {}) $ANOTHER_VARIABLE"
        echo "Secret print ${{ secret.API_KEY}}"
        echo "Step's secret variable ${SECRET_API_KEY}"
       
      env:
        SECRET_API_KEY: ${{ secret.API_KEY}}
        CONFIG_VARIABLE2: ${{env.DEPLOYMENT_ENV}}
        ANOTHER_VARIABLES: 'Some value' 